name: Upload release assets

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write
  
jobs:
  upload-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload assets to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Nordpool.js
            Translations.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
